
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '13.0'
# platform :ios, min_ios_version_supported
# platform :ios, '15.0'
prepare_react_native_project!

setup_permissions([
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'Notifications',
  'Camera',
])
# use_modular_headers!
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

target 'MyportalApp' do
  config = use_native_modules!
  
  use_react_native!(:path => config[:reactNativePath],
  :hermes_enabled => false)
  
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  target 'MyportalAppTests' do
    inherit! :complete
    # Pods for testing
  end
  pod 'Firebase/Messaging'
  # , '~> 10.18.0' 	
  pod 'Firebase/CoreOnly', '10.18.0'

  # pod 'Firebase/Firestore/', '10.18.0'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MyportalApp-tvOS' do
  # Pods for MyportalApp-tvOS

  target 'MyportalApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
